<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Пользователь добавлен</title>
</head>
<body>
<h1>${person.name}, приятно познакомиться! Твой id ${person.id}</h1>
<div>
    <a href="/">На главную</a>
</div>
</body>
</html>